#!/bin/bash

echo "The arguments passed in are : $@"

if [[ "$*" == *"--combined-json abi"* ]]
then
	    echo "YES"
    else
	        echo "NO"
fi

NEWARGS=("$@")

for i in "${!NEWARGS[@]}"
do
    if [[ "${NEWARGS[$i]}" == "--combined-json" ]]
    then
        echo -e "found combined-json flag at $i\n"
        NEXT=$(($i+1))
        echo -e "what is next value? $NEXT"
        if [[ "${NEWARGS[$NEXT]}" == "abi" ]]
        then
            echo -e "following arg is abi \n"
            NEWARGS[$NEXT]="json-abi"
        fi
    fi
done

echo $NEWARGS
#sudo docker run solidityv0.1.2 "$NEWARGS";
